### PR TITLE
Overloaded routine names

### LINKED ISSUE #36: Schema browser need better support for procedure overloading

### PR DESCRIPTION
**Pull request by davecharron**
Add support for overloaded routine names, fixes #36

### CODE REVIEW

**Comment by davecharron** [comment]
#### Functional changes in the Schema Browser
- Clicking a routine (function or procedure) properly expands to display the correct parameters for the selected routine
image
- Tool tips on routines include the specific name for differentiation when names are overloaded
  Setting the tool tip rather than changing the tree item label keeps the view cleaner yet still provides the extra info
image
- Generate SQL action changed to use the specific name so the results are only generated for the selected routine
  ( previously all routines with the same name were generated )
- Delete action changed to use the specific name so the selected routine can be deleted
  ( previously delete failed when multiple routines had the same name )

#### Setup script for testing
```sql
CREATE SCHEMA OVERLOAD;
CREATE OR REPLACE FUNCTION OVERLOAD.MULTI_FUNC (
            P1 INTEGER DEFAULT 13
    )
    RETURNS INTEGER
    LANGUAGE SQL
    MODIFIES SQL DATA
    CONCURRENT ACCESS RESOLUTION DEFAULT
    FENCED
    NOT DETERMINISTIC
    CALLED ON NULL INPUT
    EXTERNAL ACTION NOT
    SECURED
    SPECIFIC OVERLOAD.MULTI_SQ
    RETURN P1 * P1;

LABEL ON ROUTINE OVERLOAD.MULTI_FUNC(INT) IS 'Accepts One Integer and Returns Its Square';

COMMENT ON PARAMETER ROUTINE OVERLOAD.MULTI_FUNC (INT) (P1 IS 'Value to Square');


CREATE OR REPLACE FUNCTION OVERLOAD.MULTI_FUNC (
            P1 INTEGER DEFAULT 13,
            P2 INTEGER DEFAULT 74
        )
    RETURNS INTEGER
    LANGUAGE SQL
    MODIFIES SQL DATA
    CONCURRENT ACCESS RESOLUTION DEFAULT
    FENCED
    NOT DETERMINISTIC
    CALLED ON NULL INPUT
    EXTERNAL ACTION NOT
    SECURED
    SPECIFIC OVERLOAD.MULTI_PROD
    RETURN P1 * P2;

LABEL ON ROUTINE OVERLOAD.MULTI_FUNC(INT, INT) IS 'Accepts Two Integer and Returns the Product';

COMMENT ON PARAMETER ROUTINE OVERLOAD.MULTI_FUNC (INT, INT) (P1 IS 'First Value', P2 IS 'Second Value');


/* Creating OVERLOAD.MULTI_PROC [Procedure] */
CREATE OR REPLACE PROCEDURE OVERLOAD.MULTI_PROC ()
        LANGUAGE SQL
        MODIFIES SQL DATA
        SPECIFIC OVERLOAD.MULTI_MONS
        PROGRAM TYPE SUB
        CONCURRENT ACCESS RESOLUTION DEFAULT
        DYNAMIC RESULT SETS 1
        OLD SAVEPOINT LEVEL
        COMMIT ON RETURN NO
BEGIN
    DECLARE MONITORS CURSOR WITH RETURN FOR
        SELECT *
            FROM QUSRSYS.QAUGDBPMD2;
    OPEN MONITORS;
END;

/* Setting label text for OVERLOAD.MULTI_PROC */
LABEL ON SPECIFIC ROUTINE OVERLOAD.MULTI_MONS IS 'Returns the Entire List of Monitors';

/* Creating OVERLOAD.MULTI_PROC [Procedure] */
CREATE OR REPLACE PROCEDURE OVERLOAD.MULTI_PROC (
                IN CREATOR CHARACTER(10) DEFAULT ''
            )
        LANGUAGE SQL
        MODIFIES SQL DATA
        SPECIFIC OVERLOAD.MULTI_MYMONS
        PROGRAM TYPE SUB
        CONCURRENT ACCESS RESOLUTION DEFAULT
        DYNAMIC RESULT SETS 1
        OLD SAVEPOINT LEVEL
        COMMIT ON RETURN NO
BEGIN
    DECLARE MONITORS CURSOR WITH RETURN FOR
        SELECT *
            FROM QUSRSYS.QAUGDBPMD2
            WHERE "Created by" = CREATOR;
    OPEN MONITORS;
END;

/* Setting label text for OVERLOAD.MULTI_PROC */
LABEL ON SPECIFIC ROUTINE OVERLOAD.MULTI_MYMONS IS 'Returns the List of My Monitors';

/* Setting comment text for OVERLOAD.MULTI_PROC */
COMMENT ON PARAMETER SPECIFIC ROUTINE OVERLOAD.MULTI_MYMONS (CREATOR IS 'User That Created the Monitor');
```

**Review by worksofliam — CHANGES_REQUESTED** [review]
The code is fab. Let's get that instance changes where parameter markers could be used and then I will have another round of testing for you.

**Comment by davecharron** [comment]
I think I've made the required changes.  Please take another look.

**Review by worksofliam — CHANGES_REQUESTED** [review]
There is one part I'd love to see in this PR which is some tests cases that cover:

* creating the environment with the example you provided
* fetching those new functions and procedures
* checking that you can differentiate between the two functions/procedures in the API

I am happy to write those and you are welcome to also. See this test suite for how we tested the delimiter PR: 
https://github.com/halcyon-tech/vscode-db2i/blob/main/src/testing/database.ts

**Review by worksofliam — APPROVED** [review]
Tests are passing and also works in the UI! 

Great work @davecharron!

image

**Pull request merged**
