### PR TITLE
Export the `SQLJobManager` API to be used in Merlin

### PR DESCRIPTION
**Pull request by SanjulaGanepola**
### Changes
- Exported `SQLJobManager` and `SQLJob`
- Add `getAllJobs` function to the `SQLJobManager`
- Added script to generate types, but excluded them from this repo (we will manually copy over the types to our extension)

### CODE REVIEW

**Comment by SanjulaGanepola** [comment]
Closes #98

**Comment by edmundreinhardt** [comment]
The reason why I am anxious to see this get approved is because we have a dependent PR that I want to see dealt with before Sanjula returns to school next week.

**Comment by worksofliam** [comment]
@edmundreinhardt It will hopefully be this week. I still need to review but it will go in

**Comment by eric-simpson** [comment]
any update on this?

**Comment by worksofliam** [comment]
@eric-simpson stuck it into a milestone and should be merged in for a future release.

**Comment by worksofliam** [comment]
@SanjulaGanepola Sorry, we're going to need the PR to be updated against `main`. Thanks!

**Comment by SanjulaGanepola** [comment]
Updated the PR. Looks like the webpack workflow is failing due to a 403 permission error?

**Comment by worksofliam** [comment]
@SanjulaGanepola Weird. Looks like it just wasn't able to post a comment. Build still worked which is good!

**Comment by worksofliam** [comment]
Expected tests continue to pass. Thanks @SanjulaGanepola!

**Review by worksofliam — APPROVED** [review]

**Pull request merged**
