### PR TITLE
Use server-side CLI and set client special registers

### PR DESCRIPTION
**Pull request by ThePrez**

### CODE REVIEW

**Review by worksofliam — CHANGES_REQUESTED** [review]
I see what you are going for here @ThePrez - putting the version into the runtime VSIX. I believe we can (and should) do this without adding another dev dep.

In `webpack.config.js`, you can `const package = require('./package.json')` and then use the `new webpack.DefinePlugin` plugin to register an environment variable (perhaps `DB2I_VERSION) which could hold the value of `package.version`. We do this already with `process.env.DEV`.

Let me know what you think or if you have any questions.

**Comment by ThePrez** [comment]
Thanks for the guidance!

**Comment by ThePrez** [comment]
fixes #48

**Review by worksofliam — CHANGES_REQUESTED** [review]
Is it possible to write a test to ensure the client register is set? I am sure there's a way to get them with an SQL statement.

**Pull request merged**
